fix(cli): Add 'types' property to Convex tsconfig.json (#1041)
Solves the following error, which occurs when running `bun run dev:setup` after installing the Convex + Better Auth template:
```
Found 3 errors in the same file, starting at: convex/auth.ts:11
✖ TypeScript typecheck via `tsc` failed.
To ignore failing typecheck, use `--typecheck=disable`.
convex/auth.ts:11:17 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`
 and then add 'node' to the types field in your tsconfig.

11 const siteUrl = process.env.SITE_URL!;
                   ~~~~~~~
convex/auth.ts:12:22 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`
 and then add 'node' to the types field in your tsconfig.

12 const nativeAppUrl = process.env.NATIVE_APP_URL || "my-better-t-app://";
                        ~~~~~~~

convex/auth.ts:22:11 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`
 and then add 'node' to the types field in your tsconfig.

22       ...(process.env.NODE_ENV === "development"
             ~~~~~~~
```

Co-authored-by: Aman Varshney <amanvarshney.work@gmail.com>